INSERT INTO USER(USER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, PASSWORD, PHONE, EMAIL, ADDRESS, GENDER, USER_ROLE)
 VALUES(9999, 'FIRSTNAME', 'LASTNAME', '관리자', '1234', '전화번호', '이메일', '주소', '성', '관리');
 
SELECT * FROM USER;

